### ISSUE TITLE
Help with integration

### ISSUE THREAD

**Issue by mikeptweet** [shajunxing/quickjs-ffi#1]
This is an excellent addition to quickjs. How would one compile this directly into the quickjs repl as a module without requiring a shared module?

**Comment by shajunxing** [comment]
Thank you for your advice, to be honest, I didn't consider it in the beginning because in my opinion quickjs core function should keep slimmed and minimized, but of course according to some tutorials you can do some little modification on c part to integrate it into quickjs binary, but the js part I don't know how.

**Comment by shajunxing** [comment]
> This is an excellent addition to quickjs. How would one compile this directly into the quickjs repl as a module without requiring a shared module?

Thank you for your advice, to be honest, I didn't consider it in the beginning because in my opinion quickjs core function should keep slimmed and minimized, but of course according to some tutorials you can do some little modification on c part to integrate it into quickjs binary, but the js part I don't know how.
